### ISSUE TITLE
How to create dynamically step class

### ISSUE THREAD

**Issue by MrNouri** [ernestoyaquello/VerticalStepperForm#85] opened 2019-07-16 11:12 UTC
Hi, thanks for this great library.
I want create this step class dynamically from server response!
In my Api i have type and i want in special types create one of this steps!
I write below codes, but just create one of step classes !
But in API, I have 2 item of penny types and 3 items of best type!
Should show me 5 step, but show me 2 step!

**My codes :**

```
public class StepperActivity extends AppCompatActivity {

    private ApiServices apiServices;
    private ProgressBar loader;
    private VerticalStepperFormView stepper;

    private StepDynamicEdt stepDynamicEdt;
    private StepDynamicTxt stepDynamicTxt;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bidzila_stepper);
        //Initialize
        apiServices = ApiClient.ApiClient().create(ApiServices.class);
        loader = findViewById(R.id.bidStepper_loader);
        stepper = findViewById(R.id.bidStepper);

        //Api
        callAPi();
    }

    private void callAPi() {
        loader.setVisibility(View.VISIBLE);
        Call<TodayResponse> call = apiServices.TODAY_RESPONSE_CALL(5);
        call.enqueue(new Callback<TodayResponse>() {
            @Override
            public void onResponse(Call<TodayResponse> call, Response<TodayResponse> response) {
                if (response.isSuccessful()) {
                    if (response.body() != null) {
                        if (response.body().getRes() != null) {
                            if (response.body().getRes().getToday().size() > 0) {
                                loader.setVisibility(View.GONE);
                                //Foreach
                                for (int i = 0; i < response.body().getRes().getToday().size(); i++) {

                                    if (response.body().getRes().getToday().get(i).getType().equals("penny")) {

                                        stepDynamicEdt = new StepDynamicEdt(response.body().getRes().getToday().get(i).getName());

                                    } else if (response.body().getRes().getToday().get(i).getType().equals("best")) {

                                        stepDynamicTxt = new StepDynamicTxt(response.body().getRes().getToday().get(i).getName());
                                    }
                                }

                                stepper.setup(new StepperFormListener() {
                                    @Override
                                    public void onCompletedForm() {

                                    }

                                    @Override
                                    public void onCancelledForm() {

                                    }
                                }, stepDynamicEdt, stepDynamicTxt)
                                        .allowNonLinearNavigation(false)
                                        .displayCancelButtonInLastStep(false)
                                        .displayBottomNavigation(false)
                                        .confirmationStepTitle("Confirm")
                                        .stepNextButtonText("Continue")
                                        .lastStepNextButtonText("Finish")
                                        .includeConfirmationStep(false)
                                        .init();
                            }
                        }
                    }
                }
            }

            @Override
            public void onFailure(Call<TodayResponse> call, Throwable t) {
                Log.e("ResponseErr", t.getMessage());
            }
        });
    }

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(ViewPumpContextWrapper.wrap(newBase));
    }
}
```

**Comment by hassanmhd** [comment] 2019-07-30 12:57
The method `setup` has multiple implementations. One of them can be used for your case, Instead of passing `StepperFormListener ` and `args` you can create a list of steps and then pass it to the setup method as below:

```java

//Foreach
ArrayList<Step> stepsList = new ArrayList<>();
for (int i = 0; i < response.body().getRes().getToday().size(); i++) {
    if (response.body().getRes().getToday().get(i).getType().equals("penny")) {
        stepsList.add(new StepDynamicEdt(response.body().getRes().getToday().get(i).getName()));
    } else if (response.body().getRes().getToday().get(i).getType().equals("best")) {
        stepsList.add(new StepDynamicTxt(response.body().getRes().getToday().get(i).getName()));
    }
}

stepper.setup(new StepperFormListener() {
    @Override
    public void onCompletedForm() {

    }

    @Override
    public void onCancelledForm() {

    }
}, stepsList)
        .allowNonLinearNavigation(false)
        .displayCancelButtonInLastStep(false)
        .displayBottomNavigation(false)
        .confirmationStepTitle("Confirm")
        .stepNextButtonText("Continue")
        .lastStepNextButtonText("Finish")
        .includeConfirmationStep(false)
        .init();

```

Good luck! and tell me if that worked for you.

**Comment by ernestoyaquello** [comment] 2019-08-20 13:18
Unfortunately, I am not sure I understand your code or your question, but it all seems to have been solved several weeks ago, so I am going to close this issue. In any case, feel free to contact me again if you have any further questions or if you consider that the issue isn't actually resolved.

**Closed by ernestoyaquello** 2019-08-20 13:18 UTC
