### ISSUE TITLE
Getting error converting bytecode to dex

### ISSUE THREAD

**Issue by WiliamGP** [ernestoyaquello/VerticalStepperForm#75] opened 2018-12-28 02:44 UTC
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/os/ResultReceiver;
Error:com.android.dex.DexException: Multiple dex files define Landroid/support/v4/os/ResultReceiver;

How can I resolve this error?

Thanks about your library.

**Comment by ernestoyaquello** [comment] 2018-12-31 14:08
I have no idea why you are getting this error, but I am going to close the issue because this problem doesn't even seem to be related to the library.

In any case, if you really think that your issue is caused by the library, please provide more information and context and I will be glad to try to help.

**Closed by ernestoyaquello** 2018-12-31 14:08 UTC
