### ISSUE TITLE
Custom Continue message

### ISSUE THREAD

**Issue by softmarshmallow** [ernestoyaquello/VerticalStepperForm#56] opened 2017-09-08 19:03 UTC
what if i want to change button text => "CONTINUE" ??

for localization and someother reasons

**Comment by NewColours** [comment] 2018-04-01 20:32
Duplicate of #54

**Comment by ernestoyaquello** [comment] 2018-11-21 22:59
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this is now implemented in the new version of the library, please go check it out if you are still interested.

**Closed by ernestoyaquello** 2018-11-21 22:59 UTC
