### ISSUE TITLE
StepperForm show this error "This step has already been initialized"

### ISSUE THREAD

**Issue by faisalwaris** [ernestoyaquello/VerticalStepperForm#74] opened 2018-12-24 12:13 UTC
When i add two stepper view form in same activity the first stepper view working fine in first stepper view i use it as follwoing
      verticalStepperForm1
                .setup(listner1, stepperClassObject)
                .init();
In second stepper view i use it same as above but in same activity. this give me error as "This step has already been initialized"

**Comment by ernestoyaquello** [comment] 2018-12-31 14:02
Why are you using two views of type `VerticalStepperFormView` in the same activity? This library is not really designed for that, so this kind of errors are to be expected in your case.

In all fairness, I cannot even think of a scenario that would require two of these forms to be placed together. Maybe you could rethink your implementation to avoid using several stepper forms in the same screen?

Given that the issue is caused by your odd usage of the library, I am going to close the issue. However, feel free to ask me if you need any further help!

**Closed by ernestoyaquello** 2018-12-31 14:02 UTC
